/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Rom
 */
public class ApplicationGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainScreenView
     */
    public ApplicationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScreenPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        borrowManagementMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        bookManagementMenuItem = new javax.swing.JMenuItem();
        dvdMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        memberManagementMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        changePasswordMenuItem = new javax.swing.JMenuItem();
        userManagementMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library System");
        setSize(new java.awt.Dimension(1366, 768));

        mainScreenPane.setMinimumSize(new java.awt.Dimension(1366, 768));

        javax.swing.GroupLayout mainScreenPaneLayout = new javax.swing.GroupLayout(mainScreenPane);
        mainScreenPane.setLayout(mainScreenPaneLayout);
        mainScreenPaneLayout.setHorizontalGroup(
            mainScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        mainScreenPaneLayout.setVerticalGroup(
            mainScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        getContentPane().add(mainScreenPane, java.awt.BorderLayout.CENTER);

        jMenu4.setText("Borrow");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        borrowManagementMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        borrowManagementMenuItem.setText("Borrow Management");
        borrowManagementMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowManagementMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(borrowManagementMenuItem);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Catalogue");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        bookManagementMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bookManagementMenuItem.setText("Books");
        bookManagementMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookManagementMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(bookManagementMenuItem);

        dvdMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dvdMenuItem.setText("Dvds");
        dvdMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvdMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(dvdMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Members");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        memberManagementMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        memberManagementMenuItem.setText("Member Management");
        memberManagementMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberManagementMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(memberManagementMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Users");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(10, 10, 10, 10));

        changePasswordMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        changePasswordMenuItem.setText("Change Password");
        changePasswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(changePasswordMenuItem);

        userManagementMenuItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        userManagementMenuItem.setText("User Management");
        userManagementMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagementMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(userManagementMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getIFrame(JInternalFrame frame) {
        if (frame != null) {
            frame.dispose();
        }

        mainScreenPane.add(frame);
        frame.setVisible(true);
    }

    private void bookManagementMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookManagementMenuItemActionPerformed
        // TODO add your handling code here:
        getIFrame(new BookManagementIFrame());
    }//GEN-LAST:event_bookManagementMenuItemActionPerformed

    private void memberManagementMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberManagementMenuItemActionPerformed
        // TODO add your handling code here:
        getIFrame(new MemberManagementIFrame());
    }//GEN-LAST:event_memberManagementMenuItemActionPerformed

    private void userManagementMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementMenuItemActionPerformed
        // TODO add your handling code here:
        getIFrame(new UserManagementIFrame());
    }//GEN-LAST:event_userManagementMenuItemActionPerformed

    private void changePasswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordMenuItemActionPerformed
        // TODO add your handling code here:
        getIFrame(new ChangePasswordIFrame());
    }//GEN-LAST:event_changePasswordMenuItemActionPerformed

    private void dvdMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvdMenuItemActionPerformed
        // TODO add your handling code here:
        getIFrame(new DvdManagementIFrame());
    }//GEN-LAST:event_dvdMenuItemActionPerformed

    private void borrowManagementMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowManagementMenuItemActionPerformed
        // TODO add your handling code here:
        getIFrame(new BorrowManagementIFrame());
    }//GEN-LAST:event_borrowManagementMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bookManagementMenuItem;
    private javax.swing.JMenuItem borrowManagementMenuItem;
    private javax.swing.JMenuItem changePasswordMenuItem;
    private javax.swing.JMenuItem dvdMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane mainScreenPane;
    private javax.swing.JMenuItem memberManagementMenuItem;
    private javax.swing.JMenuItem userManagementMenuItem;
    // End of variables declaration//GEN-END:variables
}
